# Generated by Django 5.1 on 2026-02-11 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('niche', models.CharField(max_length=200)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stage', models.CharField(max_length=100)),
                ('vision', models.TextField()),
                ('pitch_deck', models.FileField(upload_to='pitch_decks/')),
                ('demo_video', models.URLField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('founder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
