# Generated by Django 6.0.1 on 2026-02-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startups", "0002_investmentapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="startup",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="startup",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
