# Generated by Django 5.2.10 on 2026-02-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_email_startup_phone_startup_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentapplication',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
