# Generated by Django 6.0.1 on 2026-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorprofile",
            name="industry_focus",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="investment_range_max",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="investment_range_min",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
