# Generated by Django 6.0.1 on 2026-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturers", "0002_manufacturerprofile_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturerprofile",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="manufacturerprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="manufacturerprofile",
            name="production_capacity",
            field=models.IntegerField(default=0),
        ),
    ]
